baseURL = 'https://omartinez94.github.io/gohugo-theblog/'
languageCode = 'en-us'
title = 'The Blog'
theme = "bootstrap"
relativeURLS = false

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[services]
  [services.googleAnalytics]
    id = 'G-7DCM4651L4'